### ISSUE TITLE
Collect results as blackbox in a nice, tidy way

### ISSUE THREAD

**Issue by benjspriggs** [PDXCapstoneF/SPECtate#11]
As a user of SPECtate, I'd like some idea of what's going to be produced and what's going to be used (jvm, jdk, etc) over the course of the build.

If we're doing a black box, we could see what `run.sh` or the equivalent would package up, and direct the user to that, or we might do some more managing of what artifacts we're making over the course of the benchmark.

**Comment by benjspriggs** [comment]
Related to #28 .

**Comment by Zonr0** [comment]
No longer relevant
