### ISSUE TITLE
Build commands from the json file

### ISSUE THREAD

**Issue by Zonr0** [PDXCapstoneF/SPECtate#16]
From Slack:
> Next would be building the command from the json file

> dumping the json into a command (string)* (edited)
which is easy, we just have to make sure the right params land in the right places
This could be done in a single function prob
anything else?

Edited:
> you generally want to create a list of args, and then do `subprocess.call('./run.sh', *args)`

**Comment by benjspriggs** [comment]
Used as inspiration for #24 . Closing for now until we have more to say on this.
