### ISSUE TITLE
Standardize format of JSON, python

### ISSUE THREAD

**Issue by benjspriggs** [PDXCapstoneF/SPECtate#169]
We should use something like [`jq`](https://stedolan.github.io/jq/) for formatting example JSON and [`yapf`'s google style](https://github.com/google/yapf) to format our released source.

**Comment by mbottini** [comment]
What's another dependency?

**Comment by benjspriggs** [comment]
Each of these will just be run on source, they won't need to be loaded in as dependencies.
Tutorial: <https://stedolan.github.io/jq/tutorial/>

**Comment by benjspriggs** [comment]
Closed by #184.
