### ISSUE TITLE
More up-to-date documentation on Run Types configuration

### ISSUE THREAD

**Issue by benjspriggs** [PDXCapstoneF/SPECtate#40]
Wiki: https://github.com/PDXCapstoneF/SPECtate/wiki/Conversation-on-Run-Templates

We need thorough notes on what we talked about, the goals of each key, and their purpose.
Examples needed!

**Comment by Zonr0** [comment]
Finished by @mbottini. Can be found [on a separate wiki page](https://github.com/PDXCapstoneF/SPECtate/wiki/Tate-Config)
