### ISSUE TITLE
New Main Window Design

### ISSUE THREAD

**Issue by austin-millan** [PDXCapstoneF/SPECtate#42]
Since the main window will be working mainly with runs (add/edit/delete), the main `MainWindow` frame needs some modifications. It was originally designed to manage groups/instances, but the main window should probably manage runs in a run_list.

note: There may be a way to integrate the [`render_vertical`](https://github.com/PDXCapstoneF/SPECtate/blob/am-gui_form/gui/mainGUI.py#L55) function (in `orign/am-gui_form`) to populate the second column of `MainWindow` with pairs of (labels:entries).

**Comment by Zonr0** [comment]
In progress by @lenhattu
