### ISSUE TITLE
Menu Bar Items/Commands

### ISSUE THREAD

**Issue by austin-millan** [PDXCapstoneF/SPECtate#44]
Once the file menu buttons are added, and ideally calling a function when clicked, we can go about implementing all of the called functions. 

**File Menu**
Having the above functions would allow the user to import files from anywhere and save to the local working directory.  Is this reasonable? Maybe it should it do more/less?
- [ ] `New Run List` (a command that allows user to either save the current run_list from memory [write to file], or discard all changes. Finally it would create a new {run_list_fname}.json in the current working directory (for now).
- [ ] `Add Run List` (a path that isn’t the default/hard-coded path)
- [ ] `Save Run List` (a path that isn’t the default/hard-coded path)

**Edit Menu**
Should the user be allowed to undo changes they’ve made to the run_list in memory if they haven’t written to the file? Or should users be forced to just edit each thing?
- [ ] `Undo`
- [ ] `Redo`

**Help** 
- [ ] Open Wiki a browser for github wiki pages ?

**Comment by Zonr0** [comment]
Finished and pending PR
