### ISSUE TITLE
Use python type annotations

### ISSUE THREAD

**Issue by benjspriggs** [PDXCapstoneF/SPECtate#47]
So python has types:
- <https://www.python.org/dev/peps/pep-3107>.
- Brief rundown <https://ceronman.com/2013/03/12/a-powerful-unused-feature-of-python-function-annotations/>.

Should we think to adopt this as a standard for documenting functions, or should we keep with docstrings?

**Comment by austin-millan** [comment]
Hmm, would be some refactoring work but it may be worth it... Any thoughts? I'd be happy to do this, would be better than inferring meaning from repetitive docstrings imo.

**Comment by Zonr0** [comment]
Decided in meeting this is low priority.

**Comment by benjspriggs** [comment]
We could use this in the style guide, or in the later half of the term, updating and refining the source for the final release.
