### ISSUE TITLE
SEP Data collection

### ISSUE THREAD

**Issue by benjspriggs** [PDXCapstoneF/SPECtate#49]
`run.sh` refers to `SEP` data collection, which is a little cryptic. Does anyone have any info on this? It's got something to do with `-agentpath:/workloads/JVM/libjvmtisym/libjvmtisym.so`, there's some jvm-level stuff being collected.
@D-Hiatt @mbottini

**Comment by D-Hiatt** [comment]
SEP refers to hidden Intel something or other.  As for data collection, it should just be a user provided shell executable string.  like vmstat.

**Comment by Zonr0** [comment]
Answered.
