### ISSUE TITLE
GUI for generating SPECTate configs

### ISSUE THREAD

**Issue by benjspriggs** [PDXCapstoneF/SPECtate#5]

**Comment by austin-millan** [comment]
@lenhattu 

You had a rough GUI at the start of last term right? Do you want to push it now to a new branch so others can work on it too?

**Comment by lenhattu** [comment]
@austin-millan Yes, I also had a rough CLI in the same project with the GUI. I will create a new branch. Do we have any naming convention for branches and commits? @Zonr0

**Comment by benjspriggs** [comment]
Closed as of today, since major work for the `gui` will be on hold for the time being.
