### ISSUE TITLE
Parse data from json files and construct a class object

### ISSUE THREAD

**Issue by LongLeonardoLe** [PDXCapstoneF/SPECtate#54]
parse data from json files and construct a class object

**Comment by D-Hiatt** [comment]
I've done this for my branch ht-curses in objects.py, feel free to use it.

**Comment by LongLeonardoLe** [comment]
Is that what we are going to use in the CLI as well?

**Comment by benjspriggs** [comment]
@LongLeonardoLe is this issue still open?

**Comment by D-Hiatt** [comment]
This is now complete for tate_config as well as the old spec_config format with PR #114
