### ISSUE TITLE
Add external documentation sources (ReadTheDocs, GithubPages, etc) for SPECtate

### ISSUE THREAD

**Issue by benjspriggs** [PDXCapstoneF/SPECtate#77]
As a user of SPECtate, it might be nice to have a GitHub pages to describe how things are used/ intended use cases for SPECtate.

**Comment by austin-millan** [comment]
Anyone else interested in this? I'd be happy to work on this if everyone else thinks it's worth the time, although I've never used Github pages before. 

Would this be better than .md(s) in the project repo? I've seen projects with .md files in each directory, detailing how the package is used. We also have the project Wiki.

But we may want to pick one and stick with it for the sake of consistency?

**Comment by benjspriggs** [comment]
There's an option to [serve the documentation at `docs/`](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) for GitHub pages that might be a good middle ground. IMO we should defer to using python documentation where python documentation makes sense, and use `.md` documentation for higher level documentation and usage, etc.

**Comment by austin-millan** [comment]
Well, you have my vote

**Comment by benjspriggs** [comment]
I'll make a PR with all the stuff currently in the wiki, moved to `docs/`.

**Comment by benjspriggs** [comment]
Closed since read-the-docs is getting updated in #138.
