### ISSUE TITLE
Deprecated Config Files

### ISSUE THREAD

**Issue by austin-millan** [PDXCapstoneF/SPECtate#87]
In `master` and `dev` we still have:
* example_config.json (old)
* example_spectate_config.json (old)
* runtype_options.json (old)
* tate_config.json **(new)**

I believe `dialogue.py` and various tests still reference the (old) files.

**Comment by benjspriggs** [comment]
Yeah, there's a lot of transition with where the configuration is.

**Comment by austin-millan** [comment]
Are you sure it's `example_config ` and not `tate_config`?

**Comment by benjspriggs** [comment]
`example_config` as the exclusive file for all sources should be the goal rather than the current state of things.
I'll update #72 to reflect these new changes, removing any configurations that don't make sense anymore.

**Comment by benjspriggs** [comment]
Closing since it was addressed in #72 and #100 is taking next steps on the same issue.
